DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
  id INT PRIMARY KEY,
  brand_name VARCHAR(255)
);
CREATE TABLE PRICES (
  id INT PRIMARY KEY AUTO_INCREMENT,
  brand_id INT NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  price_list INT NOT NULL,
  product_id INT NOT NULL,
  priority INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  curr CHAR(3) NOT NULL,
  FOREIGN KEY (brand_id) REFERENCES BRANDS(id)
);
